- name: Run Lychee
  uses: lycheeverse/lychee-action@v2
  with:
    # Generates the report in the step summary, but exits with code 0 instead of failing
    fail: false
    args: "--config ./lychee.toml ./README.md"